//! `thoth setup` — interactive config wizard.
//!
//! Writes `<root>/config.toml` with the user's choices. Non-interactive
//! mode accepts the same knobs as flags or falls back to defaults, so the
//! command is still usable in CI / scripted installs.

use std::io::IsTerminal;
use std::path::Path;

use anyhow::{Context, Result};
use dialoguer::{Confirm, Input, Select, theme::ColorfulTheme};

// Public knob keys — kept in sync with `DisciplineConfig`.
const MODES: &[&str] = &["soft", "strict"];
const MEMORY_MODES: &[&str] = &["auto", "review"];
const CADENCES: &[&str] = &["end", "every"];

#[derive(Clone, Debug)]
pub struct SetupAnswers {
    pub mode: String,
    pub memory_mode: String,
    pub gate_require_nudge: bool,
    pub reflect_cadence: String,
    pub gate_window_secs: u64,
    pub nudge_before_write: bool,
    pub global_fallback: bool,
}

impl Default for SetupAnswers {
    fn default() -> Self {
        Self {
            mode: "soft".to_string(),
            memory_mode: "auto".to_string(),
            gate_require_nudge: false,
            reflect_cadence: "end".to_string(),
            gate_window_secs: 180,
            nudge_before_write: true,
            global_fallback: true,
        }
    }
}

/// Run the wizard (or accept defaults) and write the config.
///
/// * If `show` is true, just print the current config and return.
/// * If `accept_defaults` is true or stdout isn't a TTY, skip prompts.
pub async fn run(root: &Path, show: bool, accept_defaults: bool) -> Result<()> {
    if show {
        return show_current(root).await;
    }

    tokio::fs::create_dir_all(root)
        .await
        .with_context(|| format!("create {}", root.display()))?;

    let non_interactive = accept_defaults || !std::io::stdout().is_terminal();
    let answers = if non_interactive {
        println!("thoth setup: non-interactive — writing defaults.");
        SetupAnswers::default()
    } else {
        prompt_interactive()?
    };

    write_config(root, &answers).await?;
    print_summary(root, &answers);
    Ok(())
}

fn prompt_interactive() -> Result<SetupAnswers> {
    let theme = ColorfulTheme::default();

    println!("thoth setup — interactive wizard");
    println!("Press enter to accept the highlighted default.\n");

    let mode_idx = Select::with_theme(&theme)
        .with_prompt("Enforcement mode")
        .items(MODES)
        .default(0)
        .interact()?;
    let mode = MODES[mode_idx].to_string();

    let memory_mode_idx = Select::with_theme(&theme)
        .with_prompt("Memory mode (auto = commit straight away, review = stage)")
        .items(MEMORY_MODES)
        .default(0)
        .interact()?;
    let memory_mode = MEMORY_MODES[memory_mode_idx].to_string();

    // Two-event gate only makes sense in strict mode. Silently default to
    // false otherwise.
    let gate_require_nudge = if mode == "strict" {
        Confirm::with_theme(&theme)
            .with_prompt("Require `thoth.nudge` before every Write/Edit/Bash? (two-event gate)")
            .default(false)
            .interact()?
    } else {
        false
    };

    let cadence_idx = Select::with_theme(&theme)
        .with_prompt("Reflect cadence (end = only on Stop, every = after each tool call)")
        .items(CADENCES)
        .default(0)
        .interact()?;
    let reflect_cadence = CADENCES[cadence_idx].to_string();

    let gate_window_secs: u64 = Input::with_theme(&theme)
        .with_prompt("Gate window in seconds (max age of a recall/nudge that still counts)")
        .default(180)
        .interact_text()?;

    let nudge_before_write = Confirm::with_theme(&theme)
        .with_prompt("Prompt the agent to expand `thoth.nudge` before Write/Edit?")
        .default(true)
        .interact()?;

    let global_fallback = Confirm::with_theme(&theme)
        .with_prompt("Fall back to `~/.thoth/` when this project has no local store?")
        .default(true)
        .interact()?;

    Ok(SetupAnswers {
        mode,
        memory_mode,
        gate_require_nudge,
        reflect_cadence,
        gate_window_secs,
        nudge_before_write,
        global_fallback,
    })
}

async fn write_config(root: &Path, a: &SetupAnswers) -> Result<()> {
    let path = root.join("config.toml");
    let body = render_toml(a);
    tokio::fs::write(&path, body)
        .await
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn render_toml(a: &SetupAnswers) -> String {
    // Keep this human-friendly — users edit it by hand later.
    format!(
        "# Generated by `thoth setup`. Edit freely; comments survive re-runs\n\
         # only if you pass `--show` (which never writes).\n\
         #\n\
         # Docs: https://github.com/unknown-studio-dev/thoth#configuration\n\
         \n\
         [memory]\n\
         # TTL (in days) for episodic log entries. 0 = keep forever.\n\
         episodic_ttl_days = 30\n\
         # Let the agent run `thoth.nudge` proactively (Mode::Full).\n\
         enable_nudge      = true\n\
         \n\
         [discipline]\n\
         # \"soft\" (warn) or \"strict\" (block via thoth-gate).\n\
         mode                     = \"{mode}\"\n\
         # Fall back to ~/.thoth when this project has no .thoth/.\n\
         global_fallback          = {global_fallback}\n\
         # \"end\" or \"every\".\n\
         reflect_cadence          = \"{reflect_cadence}\"\n\
         # Ask for thoth.nudge before every Write/Edit.\n\
         nudge_before_write       = {nudge_before_write}\n\
         # Opt-in: thoth.grounding_check on every factual claim.\n\
         grounding_check          = false\n\
         # Max age (seconds) of a recall/nudge that still satisfies the gate.\n\
         gate_window_secs         = {gate_window_secs}\n\
         \n\
         # --- v2 knobs -------------------------------------------------------\n\
         # \"auto\" commits straight to MEMORY.md/LESSONS.md.\n\
         # \"review\" stages to *.pending.md — user must promote/reject.\n\
         memory_mode              = \"{memory_mode}\"\n\
         # Strict-mode two-event gate: require thoth.nudge as well as recall.\n\
         gate_require_nudge       = {gate_require_nudge}\n\
         # Auto-quarantine lessons whose failure ratio crosses this (0.0-1.0).\n\
         quarantine_failure_ratio = 0.66\n\
         # Minimum attempts before quarantine is eligible.\n\
         quarantine_min_attempts  = 5\n",
        mode = a.mode,
        memory_mode = a.memory_mode,
        gate_require_nudge = a.gate_require_nudge,
        reflect_cadence = a.reflect_cadence,
        gate_window_secs = a.gate_window_secs,
        nudge_before_write = a.nudge_before_write,
        global_fallback = a.global_fallback,
    )
}

fn print_summary(root: &Path, a: &SetupAnswers) {
    let cfg = root.join("config.toml");
    println!("\n✓ Wrote {}", cfg.display());
    println!("  mode               = {}", a.mode);
    println!("  memory_mode        = {}", a.memory_mode);
    println!("  gate_require_nudge = {}", a.gate_require_nudge);
    println!("  reflect_cadence    = {}", a.reflect_cadence);
    println!("  gate_window_secs   = {}", a.gate_window_secs);
    println!();
    println!("Next:");
    println!("  1. thoth index .              # build the code index");
    println!("  2. thoth install              # hooks + skill + MCP in one go");
    println!("  3. Install the Cowork / Claude Code plugin (see README).");
}

async fn show_current(root: &Path) -> Result<()> {
    let path = root.join("config.toml");
    match tokio::fs::read_to_string(&path).await {
        Ok(text) => {
            println!("# {}", path.display());
            print!("{text}");
            if !text.ends_with('\n') {
                println!();
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            println!("No config.toml at {} — running defaults.", path.display());
            println!("Run `thoth setup` to create one.");
        }
        Err(e) => return Err(e).with_context(|| format!("read {}", path.display())),
    }
    Ok(())
}
